/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alpro2;

/**
 *

=======
 * @author ihsanfrr
>>>>>>> e32664b25e56b51e2b27443d5e7b200396b9965b
 */
public class HomeScreen extends javax.swing.JFrame {
    
    private int id;
    private String username;

    /**
     * Creates new form HomeScreen
     * @param id
     * @param username
     */
    public HomeScreen(int id, String username) {
        this.id = id;
        this.username = username;
        
        initComponents();
        
        greetingText.setText("Halo "+username+"!");
    }

    private HomeScreen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderProduct = new javax.swing.JButton();
        manageStock = new javax.swing.JButton();
        orderHistory = new javax.swing.JButton();
        salesReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greetingText.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        greetingText.setText("Halo Kasir!");

        jLabel2.setText("Selamat menjalankan tugas Anda dengan baik!");

        orderProduct.setBackground(new java.awt.Color(0, 191, 115));
        orderProduct.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        orderProduct.setText("Order Produk");
        orderProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductActionPerformed(evt);
            }
        });

        manageStock.setBackground(new java.awt.Color(0, 191, 115));
        manageStock.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        manageStock.setText("Kelola Stok");
        manageStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStockActionPerformed(evt);
            }
        });

        orderHistory.setBackground(new java.awt.Color(0, 191, 115));
        orderHistory.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        orderHistory.setText("Riwayat Penjualan");
        orderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryActionPerformed(evt);
            }
        });

        salesReport.setBackground(new java.awt.Color(0, 191, 115));
        salesReport.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        salesReport.setText("Laporan Penjualan");
        salesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salesReport)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manageStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderHistory))
                    .addComponent(jLabel2)
                    .addComponent(greetingText))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(greetingText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderProduct)
                    .addComponent(manageStock)
                    .addComponent(orderHistory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesReport)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductActionPerformed
        ProductOrder po = new ProductOrder(id, username);
        po.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_orderProductActionPerformed

    private void manageStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStockActionPerformed
        StockManagementScreen sm = new StockManagementScreen(id, username);
        sm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_manageStockActionPerformed

    private void orderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryActionPerformed
        OrderHistoryScreen oh = new OrderHistoryScreen(id, username);
        oh.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_orderHistoryActionPerformed

    private void salesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportActionPerformed
        SalesReportScreen sp = new SalesReportScreen(id, username);
        sp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_salesReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greetingText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageStock;
    private javax.swing.JButton orderHistory;
    private javax.swing.JButton orderProduct;
    private javax.swing.JButton salesReport;
    // End of variables declaration//GEN-END:variables
}
